MDFloatLayout:

	MDLabel:
		text:"Erreur..."
		pos_hint: {'center_y': .6}
		font_style: "H4"
		halign:"center"

	MDLabel:
		text:"Votre version de Ges_k0 n'est plus à jour. Merci de vous rendre sur la page 'tdc.ovh' afin de telecharger et installer la nouvelle image."
		pos_hint: {'center_y': .5}
		halign:"center"

	MDLabel:
		text:"Be excellent to each other"
		pos_hint: {'center_y': .1}
		halign:"center"
		color: (100,100,100,1)